# Pytorch Auto differentiation

Part of #30DaysOfBasics, I'm gonna demonstrate how pytorch powerful Auto Diff works.

In [1]:
import torch

In [4]:
t1 = torch.tensor([[1,2,3], [4,5,6]], dtype=torch.float32)
t2 = torch.ones(2,3)

t1_plus_t2 = t1 + t2

print(t1_plus_t2)

print(t1_plus_t2.grad_fn)

tensor([[2., 3., 4.],
        [5., 6., 7.]])
None


In [7]:
#including t1, t2 in CG (computational graph)

t1.requires_grad_()
t2.requires_grad_()

t1_plus_t2_dash = t1 + t2

print(t1_plus_t2_dash.grad_fn)

In [10]:
t1_plus_t2_dash.size()

torch.Size([2, 3])

In [11]:
w1.size()

torch.Size([3, 1])

In [13]:
w1 = torch.randn(3,1)

w1.requires_grad_()

p = torch.mm(t1_plus_t2_dash, w1)

s = sum(p)

print(s)

tensor([-5.9472], grad_fn=<AddBackward0>)


In [ ]:
#lets do backward propogation

#as pytorch keeps leaf tensor's gradient, not for non-leaf in order to save memory. 


s.backward()

print(t1.grad)
print(t1_plus_t2_dash.grad)
print(p.grad)



#However we can retain intermediate variable's gradient by setting .retain_grad() 

t1_plus_t2_dash.retain_grad()
s.backward()

print(t1_plus_t2_dash.grad)

In [18]:
#complete example

a = torch.randn(2,2,requires_grad=True)

b = a + 2

c = a ** 2

out = c.mean()

print(c, out)

print('*'*100)

out.backward()

print(a.grad)

tensor([[0.1885, 1.4098],
        [1.0837, 3.3648]], grad_fn=<PowBackward0>) tensor(1.5117, grad_fn=<MeanBackward0>)
****************************************************************************************************
tensor([[-0.2171, -0.5937],
        [ 0.5205, -0.9172]])
