In [38]:
import copy
import torch
import numpy as np
import pandas as pd

In [49]:
#declare a 1D tensor
x = torch.tensor([1,2,3])


#2D tensor
xx = torch.tensor([[1,2,3], [4,5,6]])


print(x)
print(xx)

print('*'*100)

print(x.size())
print(xx.size())


print('*'*100)

print(x.dtype)
print(xx.dtype)

print('*'*100)

#accessing pt content
print(xx[1][2].item())

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
****************************************************************************************************
torch.Size([3])
torch.Size([2, 3])
****************************************************************************************************
torch.int64
torch.int64
****************************************************************************************************
6


In [14]:
#chage the dtype

x = x.to(dtype = torch.float32)

print(x.dtype)

#OR

xx = xx.type(torch.DoubleTensor)
print(xx.dtype)

torch.float32
torch.float64


In [12]:
#Declare double tensor

xd = torch.DoubleTensor([[1,2,3], [4,5,6]])

print(xd.shape)
print(xd.dtype)

torch.Size([2, 3])
torch.float64


In [16]:
#checking in-place and out-place operation of changing dtype of tensor

a = torch.tensor([2])
print(a.dtype)

#NOT inplace opertion
a.to(dtype = torch.float16)
print(a.dtype)

#NOT in-place operation 
a.type(torch.DoubleTensor)
print(a.dtype)

torch.int64


In [28]:
#Reshaping the tensors

# print(xx.view(-1,6))
xx = xx.view(-1,6)
print(xx.shape)


print(xd.view(3,2))

torch.Size([1, 6])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)


In [40]:
#Numpy array

np_x = np.array([1,2,3])

print(np_x)
print(np_x.shape)
print(np_x.dtype)

print('*'*100)

#declare with different dtype
np_x1 = np.array([1,2,3], np.float32)
print(np_x1.shape)
print(np_x1.dtype)

print('*'*100)

#change numpy array dtype
np_x11 = copy.deepcopy(np_x1)
np_x11 = np_x11.astype(np.float64)
print(np_x11.shape)
print(np_x11.dtype)

[1 2 3]
(3,)
int64
****************************************************************************************************
(3,)
float32
****************************************************************************************************
(3,)
float64


In [46]:
#Numpy array and Pytorch tensors


#np to pt
np_t = torch.from_numpy(np_x1)
print(type(np_t))
print(np_t.shape)

print('*'*100)

#pt to np
pt_np = xx.numpy()
print(pt_np)
print(type(pt_np))
print(pt_np.shape)

<class 'torch.Tensor'>
torch.Size([3])
****************************************************************************************************
[[1. 2. 3. 4. 5. 6.]]
<class 'numpy.ndarray'>
(1, 6)


In [61]:
#pytorch tensors in-built matrix

one = torch.ones(10)
print(one)
print(one.shape)

zero = torch.zeros(5,7)
print(zero)
print(zero.shape)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
torch.Size([10])
tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])
torch.Size([5, 7])


In [72]:
#Random number genertion functions in torch

x_rnd = torch.rand(2) #uniform distribution [0,1)
print(x_rnd)

print('*'*100)

x_rnd_normal = torch.randn(2,2) #Normal distribution
print(x_rnd_normal)

print('*'*100)

x_rnd_interval = torch.randint(43,100, size=(3,3)) #Random int within specific interval 
print(x_rnd_interval)

print('*'*100)
x_rnd_perm = torch.randperm(30) #random permutation of integers from 0 to n-1
print(x_rnd_perm)

print('*'*100)
x_arrange = torch.arange(10, 15, 0.5)#values from the interval [start, end) taken with common difference step.
print(x_arrange)

tensor([0.3489, 0.8677])
****************************************************************************************************
tensor([[ 0.9229,  1.1036],
        [ 0.4840, -0.3887]])
****************************************************************************************************
tensor([[82, 82, 50],
        [76, 84, 95],
        [53, 56, 66]])
****************************************************************************************************
tensor([25,  5,  7, 17, 28, 12,  9, 10,  6, 26, 19, 22, 18, 15,  1, 16, 13, 20,
         4, 11, 23, 14,  8, 21, 24, 27,  3,  2,  0, 29])
****************************************************************************************************
tensor([10.0000, 10.5000, 11.0000, 11.5000, 12.0000, 12.5000, 13.0000, 13.5000,
        14.0000, 14.5000])


In [70]:
#Concantetion of tensors

a = torch.randn(3,2)
b = torch.rand(1,2)

#concat row-wise
res_row_concat = torch.cat([a, b], 0)
print(res_row_concat)


print('*'*100)

b_dash = torch.rand(3,5)

#concat col-wise
res_col_concat = torch.cat([a, b_dash], 1)
print(res_col_concat)

tensor([[ 0.0758,  0.1415],
        [ 1.1255,  0.3845],
        [ 0.7050, -0.0143],
        [ 0.0984,  0.1814]])
****************************************************************************************************
tensor([[ 0.0758,  0.1415,  0.5043,  0.4235,  0.7872,  0.9641,  0.1795],
        [ 1.1255,  0.3845,  0.3067,  0.0203,  0.8597,  0.0410,  0.7150],
        [ 0.7050, -0.0143,  0.0016,  0.9523,  0.9346,  0.6513,  0.1195]])


In [83]:
#unsqueeze operations

print(xx.shape)
xx_unseq = torch.unsqueeze(xx, 0)
print(xx_unseq.shape)

print('*'*100)

#squeeze operations
print(pt_np.shape)
pt_np_seq = pt_np.squeeze() #remove superficial 1 
print(pt_np_seq.shape)

torch.Size([2, 3])
torch.Size([1, 2, 3])
****************************************************************************************************
(1, 6)
(6,)


In [77]:
#Sum operation

a_dash = torch.arange(4 * 5 * 6).view(4,5,6) # 4*5*6 because, for 'view' operation, multiplication should be same
print(a_dash)

print('*'*100)

a_dash_sum = torch.sum(a_dash, (2,1))
print(a_dash_sum)
print(a_dash_sum.shape)

tensor([[[  0,   1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10,  11],
         [ 12,  13,  14,  15,  16,  17],
         [ 18,  19,  20,  21,  22,  23],
         [ 24,  25,  26,  27,  28,  29]],

        [[ 30,  31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40,  41],
         [ 42,  43,  44,  45,  46,  47],
         [ 48,  49,  50,  51,  52,  53],
         [ 54,  55,  56,  57,  58,  59]],

        [[ 60,  61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70,  71],
         [ 72,  73,  74,  75,  76,  77],
         [ 78,  79,  80,  81,  82,  83],
         [ 84,  85,  86,  87,  88,  89]],

        [[ 90,  91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100, 101],
         [102, 103, 104, 105, 106, 107],
         [108, 109, 110, 111, 112, 113],
         [114, 115, 116, 117, 118, 119]]])
****************************************************************************************************
tensor([ 435, 1335, 2235, 3135])
torch.Size([4])


In [ ]:
#send tensor to another device ie GPU
# b = b.cuda()